const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const NOW = new Date().toISOString();

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function write(file, content) {
  ensureDir(path.dirname(file));
  fs.writeFileSync(file, content, "utf8");
}

function mdEscape(value) {
  return String(value ?? "")
    .replace(/\|/g, "\\|")
    .replace(/\n/g, "<br>");
}

const features = {
  FR01: {
    name: "Account registration",
    pool: "A",
    endpoints: ["POST /api/register"],
    mapping: [
      ["Feature", "FR-01 Account registration"],
      ["Pool", "A - Authentication, Categories, and Products"],
      ["Primary endpoint", "POST /api/register"],
      ["Actor", "Guest user"],
      ["Authentication", "Not required"],
      ["Request body", "`name`, `email`, `password`"],
      [
        "Source of truth",
        "`README.md` FR-01, SEC-01/SEC-05; `api_specification.md` 1.1",
      ],
      [
        "Key rules",
        "name/email/password required; email format valid and unique; password >= 8 chars with uppercase/lowercase/digit/special; API success returns message and id",
      ],
      [
        "Documented ambiguity",
        "`README.md` requires confirm password at UI level, but `api_specification.md` does not expose `confirmPassword` in `POST /api/register` body; API tests record confirm-password cases as contract ambiguity rather than executable API oracle.",
      ],
    ],
    cases: [
      [
        "Domain",
        "Register with all valid fields and a unique email",
        "FR-01, API 1.1",
        "Fresh database or unique email",
        {
          name: "Nguyen Van A",
          email: "HW6.fr01.valid.001+{{$timestamp}}@example.com",
          password: "Password123!",
        },
        200,
        "JSON has message='User registered successfully' and numeric id",
        "VALID",
        "Direct positive contract case from API spec.",
      ],
      [
        "Domain",
        "Reject missing name",
        "FR-01",
        "Unique email",
        {
          email: "HW6.fr01.noname+{{$timestamp}}@example.com",
          password: "Password123!",
        },
        400,
        "Error response explains name is required",
        "INCOMPLETE",
        "AI initially omitted exact error schema because API spec only documents success; human keeps expected rejection from README requirement.",
      ],
      [
        "Domain",
        "Reject empty name",
        "FR-01",
        "Unique email",
        {
          name: "",
          email: "HW6.fr01.emptyname+{{$timestamp}}@example.com",
          password: "Password123!",
        },
        400,
        "Error response explains name is required",
        "VALID",
        "Covers required-field empty partition.",
      ],
      [
        "Domain",
        "Reject whitespace-only name",
        "FR-01",
        "Unique email",
        {
          name: "   ",
          email: "HW6.fr01.spacename+{{$timestamp}}@example.com",
          password: "Password123!",
        },
        400,
        "Error response explains name is required after trimming",
        "VALID",
        "Covers non-empty but semantically blank value.",
      ],
      [
        "Boundary",
        "Accept one-character non-empty name",
        "FR-01",
        "Unique email",
        {
          name: "A",
          email: "HW6.fr01.shortname+{{$timestamp}}@example.com",
          password: "Password123!",
        },
        200,
        "User registered successfully",
        "VALID",
        "No minimum name length is specified beyond required presence.",
      ],
      [
        "Domain",
        "Accept long but valid name",
        "FR-01",
        "Unique email",
        {
          name: "Nguyen Van A Very Long Registration Name",
          email: "HW6.fr01.longname+{{$timestamp}}@example.com",
          password: "Password123!",
        },
        200,
        "User registered successfully",
        "VALID",
        "No maximum name length is specified in the API contract.",
      ],
      [
        "Security",
        "Store/display name safely when it contains script payload",
        "SEC-04",
        "Unique email",
        {
          name: "<script>alert(1)</script>",
          email: "HW6.fr01.xssname+{{$timestamp}}@example.com",
          password: "Password123!",
        },
        200,
        "Registration succeeds or safely rejects; no script execution in downstream UI evidence",
        "INCOMPLETE",
        "API alone cannot prove UI escaping; kept as security seed for later UI observation.",
      ],
      [
        "Domain",
        "Reject missing email",
        "FR-01",
        "Unique user data",
        { name: "Missing Email", password: "Password123!" },
        400,
        "Error response explains email is required",
        "VALID",
        "Required-field missing partition.",
      ],
      [
        "Domain",
        "Reject empty email",
        "FR-01",
        "Unique user data",
        { name: "Empty Email", email: "", password: "Password123!" },
        400,
        "Error response explains valid email is required",
        "VALID",
        "Required-field empty partition.",
      ],
      [
        "Domain",
        "Reject email without at sign",
        "FR-01",
        "Unique user data",
        {
          name: "Bad Email",
          email: "bademail.example.com",
          password: "Password123!",
        },
        400,
        "Error response explains valid email format is required",
        "VALID",
        "Email format invalid partition.",
      ],
      [
        "Domain",
        "Reject email without domain",
        "FR-01",
        "Unique user data",
        { name: "Bad Email", email: "bad@", password: "Password123!" },
        400,
        "Error response explains valid email format is required",
        "VALID",
        "Email format invalid partition.",
      ],
      [
        "Domain",
        "Reject email without local part",
        "FR-01",
        "Unique user data",
        { name: "Bad Email", email: "@example.com", password: "Password123!" },
        400,
        "Error response explains valid email format is required",
        "VALID",
        "Email format invalid partition.",
      ],
      [
        "Domain",
        "Reject email with spaces",
        "FR-01",
        "Unique user data",
        {
          name: "Bad Email",
          email: "bad email@example.com",
          password: "Password123!",
        },
        400,
        "Error response explains valid email format is required",
        "VALID",
        "Email format invalid partition.",
      ],
      [
        "Domain",
        "Accept plus-tag valid email",
        "FR-01",
        "Unique email",
        {
          name: "Plus Email",
          email: "HW6.fr01.plus+tag+{{$timestamp}}@example.com",
          password: "Password123!",
        },
        200,
        "User registered successfully",
        "VALID",
        "Valid email representative with plus addressing.",
      ],
      [
        "Domain",
        "Accept mixed-case valid email",
        "FR-01",
        "Unique email",
        {
          name: "Case Email",
          email: "HW6.Fr01.Mixed+{{$timestamp}}@Example.COM",
          password: "Password123!",
        },
        200,
        "User registered successfully",
        "VALID",
        "Valid email representative; uniqueness behavior is observable.",
      ],
      [
        "Domain",
        "Reject duplicate email",
        "FR-01",
        "Pre-create account with same email",
        {
          name: "Duplicate User",
          email: "HW6.fr01.duplicate@example.com",
          password: "Password123!",
        },
        400,
        "Second registration is rejected because email must be unique",
        "VALID",
        "Uniqueness partition from README.",
      ],
      [
        "Security",
        "Reject SQL injection-looking email without server error",
        "SEC-05",
        "Unique user data",
        {
          name: "SQL Email",
          email: "' OR '1'='1@example.com",
          password: "Password123!",
        },
        400,
        "No auth bypass or database error; safe JSON error",
        "VALID",
        "Parameterized query/security probe.",
      ],
      [
        "Security",
        "Reject SQL injection-looking name without server error",
        "SEC-05",
        "Unique email",
        {
          name: "Robert'); DROP TABLE users;--",
          email: "HW6.fr01.sqlname+{{$timestamp}}@example.com",
          password: "Password123!",
        },
        200,
        "Registration succeeds or safely rejects; database remains available",
        "VALID",
        "Injection payload in name should not break database.",
      ],
      [
        "Domain",
        "Reject missing password",
        "FR-01",
        "Unique email",
        {
          name: "No Password",
          email: "HW6.fr01.nopass+{{$timestamp}}@example.com",
        },
        400,
        "Error response explains password is required",
        "VALID",
        "Required-field missing partition.",
      ],
      [
        "Domain",
        "Reject empty password",
        "FR-01",
        "Unique email",
        {
          name: "Empty Password",
          email: "HW6.fr01.emptypass+{{$timestamp}}@example.com",
          password: "",
        },
        400,
        "Error response explains password is required/weak",
        "VALID",
        "Required-field empty partition.",
      ],
      [
        "Boundary",
        "Reject password length 7",
        "FR-01",
        "Unique email",
        {
          name: "Short Password",
          email: "HW6.fr01.shortpass+{{$timestamp}}@example.com",
          password: "Aa1!aaa",
        },
        400,
        "Password length boundary below 8 rejected",
        "VALID",
        "BVA below lower bound.",
      ],
      [
        "Boundary",
        "Accept password length 8 with all required classes",
        "FR-01",
        "Unique email",
        {
          name: "Eight Password",
          email: "HW6.fr01.eightpass+{{$timestamp}}@example.com",
          password: "Aa1!aaaa",
        },
        200,
        "User registered successfully",
        "VALID",
        "BVA on lower bound.",
      ],
      [
        "Domain",
        "Reject password missing uppercase",
        "FR-01",
        "Unique email",
        {
          name: "No Upper",
          email: "HW6.fr01.noupper+{{$timestamp}}@example.com",
          password: "password123!",
        },
        400,
        "Password complexity rejection",
        "VALID",
        "Missing uppercase partition.",
      ],
      [
        "Domain",
        "Reject password missing lowercase",
        "FR-01",
        "Unique email",
        {
          name: "No Lower",
          email: "HW6.fr01.nolower+{{$timestamp}}@example.com",
          password: "PASSWORD123!",
        },
        400,
        "Password complexity rejection",
        "VALID",
        "Missing lowercase partition.",
      ],
      [
        "Domain",
        "Reject password missing digit",
        "FR-01",
        "Unique email",
        {
          name: "No Digit",
          email: "HW6.fr01.nodigit+{{$timestamp}}@example.com",
          password: "Password!",
        },
        400,
        "Password complexity rejection",
        "VALID",
        "Missing digit partition.",
      ],
      [
        "Domain",
        "Reject password missing special character",
        "FR-01",
        "Unique email",
        {
          name: "No Special",
          email: "HW6.fr01.nospecial+{{$timestamp}}@example.com",
          password: "Password123",
        },
        400,
        "Password complexity rejection",
        "VALID",
        "Missing special-character partition.",
      ],
      [
        "Domain",
        "Accept password with @ special character",
        "FR-01",
        "Unique email",
        {
          name: "At Special",
          email: "HW6.fr01.atpass+{{$timestamp}}@example.com",
          password: "Password123@",
        },
        200,
        "User registered successfully",
        "VALID",
        "Allowed special character representative.",
      ],
      [
        "Domain",
        "Accept password with dollar special character",
        "FR-01",
        "Unique email",
        {
          name: "Dollar Special",
          email: "HW6.fr01.dollarpass+{{$timestamp}}@example.com",
          password: "Password123$",
        },
        200,
        "User registered successfully",
        "VALID",
        "Allowed special character representative.",
      ],
      [
        "Domain",
        "Accept password with ampersand special character",
        "FR-01",
        "Unique email",
        {
          name: "Amp Special",
          email: "HW6.fr01.amppass+{{$timestamp}}@example.com",
          password: "Password123&",
        },
        200,
        "User registered successfully",
        "VALID",
        "Allowed special character representative.",
      ],
      [
        "Schema",
        "Success response schema contains only message and numeric id",
        "API 1.1",
        "Unique valid user",
        {
          name: "Schema User",
          email: "HW6.fr01.schema+{{$timestamp}}@example.com",
          password: "Password123!",
        },
        200,
        "JSON object with string message and number id; no password field",
        "VALID",
        "Schema validation case.",
      ],
      [
        "Security",
        "Success response must not expose password",
        "SEC-01",
        "Unique valid user",
        {
          name: "No Leak",
          email: "HW6.fr01.noleak+{{$timestamp}}@example.com",
          password: "Password123!",
        },
        200,
        "Response does not contain password or password hash",
        "VALID",
        "Observable sensitive data leakage check.",
      ],
      [
        "Domain",
        "Reject null name",
        "FR-01",
        "Unique email",
        {
          name: null,
          email: "HW6.fr01.nullname+{{$timestamp}}@example.com",
          password: "Password123!",
        },
        400,
        "Name validation error",
        "VALID",
        "Null partition.",
      ],
      [
        "Domain",
        "Reject null email",
        "FR-01",
        "Unique user data",
        { name: "Null Email", email: null, password: "Password123!" },
        400,
        "Email validation error",
        "VALID",
        "Null partition.",
      ],
      [
        "Domain",
        "Reject null password",
        "FR-01",
        "Unique email",
        {
          name: "Null Password",
          email: "HW6.fr01.nullpass+{{$timestamp}}@example.com",
          password: null,
        },
        400,
        "Password validation error",
        "VALID",
        "Null partition.",
      ],
      [
        "Domain",
        "Reject unexpected role field during registration",
        "SEC-03",
        "Unique email",
        {
          name: "Role Injection",
          email: "HW6.fr01.role+{{$timestamp}}@example.com",
          password: "Password123!",
          role: "admin",
        },
        400,
        "Registration rejects role injection or ignores role; created user is not admin",
        "INCOMPLETE",
        "AI recognized role escalation but needs follow-up login/profile check to prove no admin role.",
      ],
      [
        "Human-Added",
        "Verify duplicate email using exact two-step setup in one run",
        "FR-01",
        "Collection creates first user then submits same email again",
        {
          name: "Duplicate Exact",
          email: "HW6.fr01.dup.exact@example.com",
          password: "Password123!",
        },
        400,
        "Second request rejects duplicate email without 500",
        "Human-Added",
        "AI listed duplicate conceptually but missed deterministic setup dependency for an executable Newman run.",
      ],
      [
        "Human-Added",
        "Reject body with only unknown properties",
        "FR-01",
        "None",
        {
          fullName: "Unknown",
          mail: "unknown@example.com",
          pass: "Password123!",
        },
        400,
        "Unknown-property-only body is rejected",
        "Human-Added",
        "AI missed API contract robustness for malformed JSON shape.",
      ],
      [
        "Human-Added",
        "Reject array JSON body",
        "FR-01",
        "None",
        [
          {
            name: "Array User",
            email: "array@example.com",
            password: "Password123!",
          },
        ],
        400,
        "Array body is rejected with safe JSON error",
        "Human-Added",
        "AI missed wrong top-level JSON type.",
      ],
      [
        "Human-Added",
        "Reject boolean password type",
        "FR-01",
        "Unique email",
        {
          name: "Boolean Password",
          email: "HW6.fr01.boolpass+{{$timestamp}}@example.com",
          password: true,
        },
        400,
        "Password type validation error",
        "Human-Added",
        "AI focused on string complexity but missed non-string type partition.",
      ],
      [
        "Human-Added",
        "Check API/README confirm-password contradiction",
        "FR-01",
        "None",
        {
          name: "Confirm Missing",
          email: "HW6.fr01.confirm+{{$timestamp}}@example.com",
          password: "Password123!",
        },
        200,
        "API may succeed because confirmPassword is not in API spec; report UI/API contract ambiguity separately",
        "Human-Added",
        "AI initially turned UI confirm-password rule into an API oracle without noting the contract mismatch.",
      ],
    ],
  },
  FR07: {
    name: "Shopping cart",
    pool: "B",
    endpoints: ["GET /api/cart", "POST /api/cart"],
    mapping: [
      ["Feature", "FR-07 Shopping cart"],
      ["Pool", "B - Shopping Cart and Checkout"],
      ["Primary endpoints", "GET /api/cart; POST /api/cart"],
      ["Actor", "Authenticated user"],
      ["Authentication", "Required JWT token"],
      ["Request body", "`id`, `name`, `price`, `quantity` for add-to-cart"],
      [
        "Source of truth",
        "`README.md` FR-07, SEC-02/SEC-05; `api_specification.md` 4.1, 4.2",
      ],
      [
        "Key rules",
        "Cart requires token; adding same product increases quantity instead of adding duplicate row; item data includes product/unit price/quantity; quantity is positive integer by FR-06/FR-07 interaction",
      ],
      [
        "Documented ambiguity",
        "API spec exposes add and get cart only; UI-only remove/confirmation/total-label requirements are recorded as non-API coverage notes.",
      ],
    ],
    cases: [
      [
        "Security",
        "Reject GET cart without token",
        "SEC-02, API 4.1",
        "None",
        { method: "GET", token: "none" },
        401,
        "Unauthorized JSON error",
        "VALID",
        "Protected endpoint missing-token case.",
      ],
      [
        "Security",
        "Reject GET cart with malformed token",
        "SEC-02",
        "None",
        { method: "GET", token: "malformed" },
        403,
        "Forbidden JSON error",
        "VALID",
        "Protected endpoint invalid-token case.",
      ],
      [
        "Security",
        "Accept GET cart with valid user token",
        "SEC-02, API 4.1",
        "Login as test user",
        { method: "GET", token: "user" },
        200,
        "JSON array cart",
        "VALID",
        "Positive protected endpoint case.",
      ],
      [
        "Schema",
        "GET empty cart response is an array",
        "API 4.1",
        "Fresh server memory or new user",
        { method: "GET", token: "user" },
        200,
        "Response is array",
        "VALID",
        "Schema baseline.",
      ],
      [
        "Domain",
        "Add valid product with quantity 1",
        "FR-07, API 4.2",
        "Login as user",
        { id: 1, name: "iPhone 15 Pro Max", price: 30000000, quantity: 1 },
        200,
        "message='Added to cart'",
        "VALID",
        "Positive add-to-cart case.",
      ],
      [
        "Domain",
        "Add valid product with quantity 2",
        "FR-07, API 4.2",
        "Login as user",
        { id: 1, name: "iPhone 15 Pro Max", price: 30000000, quantity: 2 },
        200,
        "message='Added to cart'",
        "VALID",
        "Positive quantity case.",
      ],
      [
        "Boundary",
        "Reject quantity 0",
        "FR-06/FR-07",
        "Login as user",
        { id: 1, name: "iPhone 15 Pro Max", price: 30000000, quantity: 0 },
        400,
        "Quantity must be positive integer",
        "VALID",
        "BVA below minimum.",
      ],
      [
        "Boundary",
        "Reject quantity -1",
        "FR-06/FR-07",
        "Login as user",
        { id: 1, name: "iPhone 15 Pro Max", price: 30000000, quantity: -1 },
        400,
        "Quantity must be positive integer",
        "VALID",
        "Negative range invalid.",
      ],
      [
        "Domain",
        "Reject decimal quantity",
        "FR-06/FR-07",
        "Login as user",
        { id: 1, name: "iPhone 15 Pro Max", price: 30000000, quantity: 1.5 },
        400,
        "Quantity must be integer",
        "VALID",
        "Wrong numeric precision.",
      ],
      [
        "Domain",
        "Reject string quantity",
        "FR-06/FR-07",
        "Login as user",
        { id: 1, name: "iPhone 15 Pro Max", price: 30000000, quantity: "2" },
        400,
        "Quantity must be number",
        "VALID",
        "Wrong type partition.",
      ],
      [
        "Domain",
        "Reject missing quantity",
        "FR-07, API 4.2",
        "Login as user",
        { id: 1, name: "iPhone 15 Pro Max", price: 30000000 },
        400,
        "Quantity is required",
        "VALID",
        "Required-field missing partition.",
      ],
      [
        "Domain",
        "Reject null quantity",
        "FR-07",
        "Login as user",
        { id: 1, name: "iPhone 15 Pro Max", price: 30000000, quantity: null },
        400,
        "Quantity is required",
        "VALID",
        "Null partition.",
      ],
      [
        "Domain",
        "Reject missing product id",
        "API 4.2",
        "Login as user",
        { name: "iPhone 15 Pro Max", price: 30000000, quantity: 1 },
        400,
        "Product id is required",
        "VALID",
        "Required-field missing partition.",
      ],
      [
        "Domain",
        "Reject null product id",
        "API 4.2",
        "Login as user",
        { id: null, name: "iPhone 15 Pro Max", price: 30000000, quantity: 1 },
        400,
        "Product id is required",
        "VALID",
        "Null partition.",
      ],
      [
        "Domain",
        "Reject string product id",
        "API 4.2",
        "Login as user",
        { id: "abc", name: "iPhone 15 Pro Max", price: 30000000, quantity: 1 },
        400,
        "Product id must be numeric",
        "VALID",
        "Wrong type partition.",
      ],
      [
        "Domain",
        "Reject non-existing product id",
        "FR-07",
        "Login as user",
        { id: 999999, name: "Ghost Product", price: 100000, quantity: 1 },
        404,
        "Product not found",
        "INCOMPLETE",
        "API spec does not state product lookup behavior; kept as requirement-derived data integrity case.",
      ],
      [
        "Domain",
        "Reject missing product name",
        "API 4.2",
        "Login as user",
        { id: 1, price: 30000000, quantity: 1 },
        400,
        "Product name is required",
        "VALID",
        "Required-field missing partition.",
      ],
      [
        "Domain",
        "Reject empty product name",
        "API 4.2",
        "Login as user",
        { id: 1, name: "", price: 30000000, quantity: 1 },
        400,
        "Product name is required",
        "VALID",
        "Required-field empty partition.",
      ],
      [
        "Security",
        "Store/display product name safely when script payload is submitted",
        "SEC-04",
        "Login as user",
        {
          id: 1,
          name: "<img src=x onerror=alert(1)>",
          price: 30000000,
          quantity: 1,
        },
        400,
        "Unsafe name rejected or safely stored for escaped rendering",
        "INCOMPLETE",
        "API execution can capture storage behavior; UI escaping needs later observation.",
      ],
      [
        "Domain",
        "Reject missing price",
        "API 4.2",
        "Login as user",
        { id: 1, name: "iPhone 15 Pro Max", quantity: 1 },
        400,
        "Price is required",
        "VALID",
        "Required-field missing partition.",
      ],
      [
        "Boundary",
        "Reject price 0",
        "FR-15 product price rule by data integrity",
        "Login as user",
        { id: 1, name: "iPhone 15 Pro Max", price: 0, quantity: 1 },
        400,
        "Price must be positive",
        "VALID",
        "BVA below valid positive price.",
      ],
      [
        "Boundary",
        "Reject negative price",
        "FR-15 product price rule by data integrity",
        "Login as user",
        { id: 1, name: "iPhone 15 Pro Max", price: -1, quantity: 1 },
        400,
        "Price must be positive",
        "VALID",
        "Invalid negative price.",
      ],
      [
        "Domain",
        "Reject string price",
        "API 4.2",
        "Login as user",
        { id: 1, name: "iPhone 15 Pro Max", price: "30000000", quantity: 1 },
        400,
        "Price must be numeric",
        "VALID",
        "Wrong type partition.",
      ],
      [
        "Security",
        "Reject POST cart without token",
        "SEC-02, API 4.2",
        "None",
        {
          id: 1,
          name: "iPhone 15 Pro Max",
          price: 30000000,
          quantity: 1,
          token: "none",
        },
        401,
        "Unauthorized JSON error",
        "VALID",
        "Protected endpoint missing-token case.",
      ],
      [
        "Security",
        "Reject POST cart with malformed token",
        "SEC-02",
        "None",
        {
          id: 1,
          name: "iPhone 15 Pro Max",
          price: 30000000,
          quantity: 1,
          token: "malformed",
        },
        403,
        "Forbidden JSON error",
        "VALID",
        "Invalid-token case.",
      ],
      [
        "State",
        "Adding same product twice increases quantity, not duplicate row",
        "FR-07",
        "Login as user; cart has product id 1 quantity 1",
        { id: 1, name: "iPhone 15 Pro Max", price: 30000000, quantity: 1 },
        200,
        "Follow-up GET shows one row for id=1 with combined quantity",
        "VALID",
        "Core FR-07 state behavior.",
      ],
      [
        "State",
        "Repeated GET cart does not mutate cart contents",
        "FR-07/API 4.1",
        "Login as user; cart may contain items",
        { method: "GET", token: "user" },
        200,
        "Two consecutive GET responses preserve the same cart item count",
        "VALID",
        "Read-only endpoint state stability check.",
      ],
      [
        "State",
        "Adding different product creates separate row",
        "FR-07",
        "Login as user; cart has product id 1",
        {
          id: 2,
          name: "Samsung Galaxy S24 Ultra",
          price: 28000000,
          quantity: 1,
        },
        200,
        "Follow-up GET includes ids 1 and 2",
        "VALID",
        "Distinct product state behavior.",
      ],
      [
        "Schema",
        "POST cart success schema has message only",
        "API 4.2",
        "Login as user",
        { id: 3, name: "MacBook Pro M3", price: 45000000, quantity: 1 },
        200,
        "JSON object with string message",
        "VALID",
        "Response schema validation.",
      ],
      [
        "Schema",
        "GET cart item schema",
        "API 4.1/4.2",
        "Cart contains at least one item",
        { method: "GET", token: "user" },
        200,
        "Each item has id, name, price, quantity with correct types",
        "VALID",
        "Cart response schema validation.",
      ],
      [
        "Security",
        "Cart is isolated per user",
        "SEC-02",
        "Two registered/login users",
        { userAAdds: 1, userBReads: true },
        200,
        "User B cart does not contain User A item",
        "INCOMPLETE",
        "Requires second user/token setup in collection.",
      ],
      [
        "Security",
        "Reject role or user_id injection in cart body",
        "SEC-02/SEC-03",
        "Login as user",
        {
          id: 1,
          name: "iPhone 15 Pro Max",
          price: 30000000,
          quantity: 1,
          user_id: 1,
          role: "admin",
        },
        400,
        "Server ignores/rejects identity fields from body",
        "VALID",
        "Client must not control identity via body.",
      ],
      [
        "Security",
        "Reject SQL injection-looking product name safely",
        "SEC-05",
        "Login as user",
        {
          id: 1,
          name: "x'); DROP TABLE carts;--",
          price: 30000000,
          quantity: 1,
        },
        400,
        "No database error/server crash",
        "VALID",
        "Injection payload safety.",
      ],
      [
        "Data-driven",
        "Run quantity boundaries from data file",
        "FR-06/FR-07",
        "Login as user",
        { quantityCases: [-1, 0, 1, 2] },
        200,
        "Only positive integer rows pass",
        "VALID",
        "Data-driven Postman runner coverage.",
      ],
      [
        "Domain",
        "Reject empty object body",
        "API 4.2",
        "Login as user",
        {},
        400,
        "Validation error for required cart fields",
        "VALID",
        "Malformed body partition.",
      ],
      [
        "Human-Added",
        "Reject array body",
        "API 4.2",
        "Login as user",
        [{ id: 1, name: "iPhone", price: 30000000, quantity: 1 }],
        400,
        "Array body rejected",
        "Human-Added",
        "AI missed wrong top-level JSON type.",
      ],
      [
        "Human-Added",
        "Reject extremely large quantity",
        "FR-07",
        "Login as user",
        {
          id: 1,
          name: "iPhone 15 Pro Max",
          price: 30000000,
          quantity: 999999999,
        },
        400,
        "Unreasonable quantity rejected or capped",
        "Human-Added",
        "AI covered boundaries near zero but missed abuse-scale values.",
      ],
      [
        "Human-Added",
        "Reject mismatched product name for valid id",
        "FR-07 data integrity",
        "Login as user",
        { id: 1, name: "Fake Product Name", price: 30000000, quantity: 1 },
        400,
        "Server does not trust client-supplied product name",
        "Human-Added",
        "AI assumed client body was authoritative and missed ID/body consistency.",
      ],
      [
        "Human-Added",
        "Reject mismatched product price for valid id",
        "FR-07 data integrity",
        "Login as user",
        { id: 1, name: "iPhone 15 Pro Max", price: 1, quantity: 1 },
        400,
        "Server does not trust client-supplied price",
        "Human-Added",
        "AI missed price tampering risk that affects checkout total.",
      ],
      [
        "Human-Added",
        "Verify `X-Student-Id` header is present on cart requests",
        "HW6 anti-cheat",
        "Collection-level header configured",
        { header: "X-Student-Id" },
        200,
        "Request console/Newman evidence shows header value",
        "Human-Added",
        "AI often treats assignment evidence headers as tooling detail, not a test artifact.",
      ],
    ],
  },
  FR17: {
    name: "Coupon management CRUD",
    pool: "C",
    endpoints: [
      "GET /api/coupons",
      "POST /api/admin/coupons",
      "DELETE /api/admin/coupons/:id",
    ],
    mapping: [
      ["Feature", "FR-17 Coupon management CRUD"],
      ["Pool", "C - Web Admin"],
      [
        "Primary endpoints",
        "GET /api/coupons; POST /api/admin/coupons; DELETE /api/admin/coupons/:id",
      ],
      ["Actor", "Admin"],
      ["Authentication", "Valid JWT with role=admin required by FR-12/SEC-03"],
      [
        "Request body",
        "`code`, `type`, `discount_value`, `expired_at`, `min_order_amount`, `max_uses_per_user`",
      ],
      [
        "Source of truth",
        "`README.md` FR-12/FR-17, SEC-02/SEC-03/SEC-05; `api_specification.md` 5.2, 6.4",
      ],
      [
        "Key rules",
        "Admin can add/view/delete coupons; required fields; `code` unique; `type` percent/fixed; positive discount; `min_order_amount >= 0`; `max_uses_per_user >= 1`",
      ],
      [
        "Documented ambiguity",
        "`api_specification.md` lists `GET /api/coupons` as admin endpoint with Authorization header, while route path is not under `/api/admin`; FR-12 still requires admin role for admin coupon management.",
      ],
    ],
    cases: [
      [
        "Security",
        "Reject GET coupons without token",
        "SEC-02, API 5.2",
        "None",
        { method: "GET", token: "none" },
        401,
        "Unauthorized JSON error",
        "VALID",
        "Protected endpoint missing-token case.",
      ],
      [
        "Security",
        "Reject GET coupons with malformed token",
        "SEC-02",
        "None",
        { method: "GET", token: "malformed" },
        403,
        "Forbidden JSON error",
        "VALID",
        "Invalid-token case.",
      ],
      [
        "Security",
        "Reject GET coupons with user token",
        "SEC-03/FR-12",
        "Login as normal user",
        { method: "GET", token: "user" },
        403,
        "User role cannot access admin coupon list",
        "VALID",
        "Role enforcement case.",
      ],
      [
        "Security",
        "Accept GET coupons with admin token",
        "FR-17/API 5.2",
        "Login as admin",
        { method: "GET", token: "admin" },
        200,
        "JSON array of coupons",
        "VALID",
        "Positive admin list case.",
      ],
      [
        "Schema",
        "GET coupons item schema",
        "API 5.2",
        "Admin token",
        { method: "GET", token: "admin" },
        200,
        "Each coupon has id, code, type, discount_value, min_order_amount, expired_at, is_active, max_uses_per_user",
        "VALID",
        "Schema validation.",
      ],
      [
        "Security",
        "Reject POST coupon without token",
        "SEC-02/API 6.4",
        "None",
        { token: "none" },
        401,
        "Unauthorized JSON error",
        "VALID",
        "Protected mutation missing-token case.",
      ],
      [
        "Security",
        "Reject POST coupon with malformed token",
        "SEC-02/API 6.4",
        "None",
        { token: "malformed" },
        403,
        "Forbidden JSON error",
        "VALID",
        "Invalid-token case.",
      ],
      [
        "Security",
        "Reject POST coupon with user token",
        "SEC-03/FR-12",
        "Login as normal user",
        { token: "user" },
        403,
        "User role cannot create admin coupon",
        "VALID",
        "Role enforcement case.",
      ],
      [
        "Domain",
        "Create valid percent coupon",
        "FR-17/API 6.4",
        "Admin token; unique code",
        {
          code: "HW6P{{$timestamp}}",
          type: "percent",
          discount_value: 15,
          min_order_amount: 200000,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        200,
        "message='Coupon created' and numeric id",
        "VALID",
        "Positive create percent case.",
      ],
      [
        "Domain",
        "Create valid fixed coupon",
        "FR-17/API 6.4",
        "Admin token; unique code",
        {
          code: "HW6F{{$timestamp}}",
          type: "fixed",
          discount_value: 50000,
          min_order_amount: 200000,
          expired_at: "2099-12-31",
          max_uses_per_user: 2,
        },
        200,
        "message='Coupon created' and numeric id",
        "VALID",
        "Positive create fixed case.",
      ],
      [
        "Domain",
        "Reject missing code",
        "FR-17",
        "Admin token",
        {
          type: "percent",
          discount_value: 10,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "Code is required",
        "VALID",
        "Required-field missing partition.",
      ],
      [
        "Domain",
        "Reject empty code",
        "FR-17",
        "Admin token",
        {
          code: "",
          type: "percent",
          discount_value: 10,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "Code is required",
        "VALID",
        "Required-field empty partition.",
      ],
      [
        "Domain",
        "Reject whitespace-only code",
        "FR-17",
        "Admin token",
        {
          code: "   ",
          type: "percent",
          discount_value: 10,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "Code is required after trimming",
        "VALID",
        "Semantically blank value.",
      ],
      [
        "Domain",
        "Reject duplicate code",
        "FR-17",
        "Admin token; SAVE10 exists",
        {
          code: "SAVE10",
          type: "percent",
          discount_value: 10,
          min_order_amount: 300000,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "Duplicate code rejected without server error",
        "VALID",
        "Uniqueness partition.",
      ],
      [
        "Domain",
        "Reject invalid type value",
        "FR-17",
        "Admin token",
        {
          code: "BADTYPE{{$timestamp}}",
          type: "bogus",
          discount_value: 10,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "Type must be percent or fixed",
        "VALID",
        "Enum invalid partition.",
      ],
      [
        "Domain",
        "Reject missing type",
        "FR-17",
        "Admin token",
        {
          code: "NOTYPE{{$timestamp}}",
          discount_value: 10,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "Type is required",
        "VALID",
        "Required-field missing partition.",
      ],
      [
        "Domain",
        "Reject uppercase type if enum is case-sensitive",
        "FR-17",
        "Admin token",
        {
          code: "UPTYPE{{$timestamp}}",
          type: "PERCENT",
          discount_value: 10,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "Type must match documented percent/fixed values",
        "INCOMPLETE",
        "API spec does not state case-sensitivity; human keeps as assumption.",
      ],
      [
        "Domain",
        "Reject missing discount_value",
        "FR-17",
        "Admin token",
        {
          code: "NOVALUE{{$timestamp}}",
          type: "percent",
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "discount_value is required",
        "VALID",
        "Required-field missing partition.",
      ],
      [
        "Boundary",
        "Reject discount_value 0",
        "FR-17",
        "Admin token",
        {
          code: "ZEROVAL{{$timestamp}}",
          type: "percent",
          discount_value: 0,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "discount_value must be positive",
        "VALID",
        "BVA below positive range.",
      ],
      [
        "Boundary",
        "Reject negative discount_value",
        "FR-17",
        "Admin token",
        {
          code: "NEGVAL{{$timestamp}}",
          type: "fixed",
          discount_value: -1,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "discount_value must be positive",
        "VALID",
        "Invalid negative partition.",
      ],
      [
        "Domain",
        "Reject string discount_value",
        "FR-17",
        "Admin token",
        {
          code: "STRINGVAL{{$timestamp}}",
          type: "fixed",
          discount_value: "50000",
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "discount_value must be numeric",
        "VALID",
        "Wrong type partition.",
      ],
      [
        "Boundary",
        "Reject percent discount over 100",
        "FR-17 business sanity",
        "Admin token",
        {
          code: "PCT101{{$timestamp}}",
          type: "percent",
          discount_value: 101,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "Percent discount must not exceed 100",
        "INCOMPLETE",
        "Not explicit in README, but derived as business sanity; mark assumption.",
      ],
      [
        "Domain",
        "Reject missing expired_at",
        "FR-17",
        "Admin token",
        {
          code: "NOEXP{{$timestamp}}",
          type: "percent",
          discount_value: 10,
          min_order_amount: 0,
          max_uses_per_user: 1,
        },
        400,
        "expired_at is required",
        "VALID",
        "Required-field missing partition.",
      ],
      [
        "Domain",
        "Reject invalid expired_at format",
        "FR-17",
        "Admin token",
        {
          code: "BADEXP{{$timestamp}}",
          type: "percent",
          discount_value: 10,
          min_order_amount: 0,
          expired_at: "not-a-date",
          max_uses_per_user: 1,
        },
        400,
        "expired_at must be valid date",
        "VALID",
        "Date format invalid partition.",
      ],
      [
        "Boundary",
        "Accept future expired_at date",
        "FR-17",
        "Admin token",
        {
          code: "FUTURE{{$timestamp}}",
          type: "percent",
          discount_value: 10,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        200,
        "Coupon created",
        "VALID",
        "Valid future date case.",
      ],
      [
        "Domain",
        "Reject missing min_order_amount",
        "FR-17",
        "Admin token",
        {
          code: "NOMIN{{$timestamp}}",
          type: "fixed",
          discount_value: 50000,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "min_order_amount is required",
        "VALID",
        "Required-field missing partition.",
      ],
      [
        "Boundary",
        "Accept min_order_amount 0",
        "FR-17",
        "Admin token",
        {
          code: "MINZERO{{$timestamp}}",
          type: "fixed",
          discount_value: 50000,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        200,
        "Coupon created",
        "VALID",
        "BVA on inclusive lower bound.",
      ],
      [
        "Boundary",
        "Reject min_order_amount -1",
        "FR-17",
        "Admin token",
        {
          code: "MINNEG{{$timestamp}}",
          type: "fixed",
          discount_value: 50000,
          min_order_amount: -1,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "min_order_amount must be >= 0",
        "VALID",
        "BVA below lower bound.",
      ],
      [
        "Domain",
        "Reject string min_order_amount",
        "FR-17",
        "Admin token",
        {
          code: "MINSTR{{$timestamp}}",
          type: "fixed",
          discount_value: 50000,
          min_order_amount: "0",
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "min_order_amount must be numeric",
        "VALID",
        "Wrong type partition.",
      ],
      [
        "Domain",
        "Reject missing max_uses_per_user",
        "FR-17",
        "Admin token",
        {
          code: "NOUSAGE{{$timestamp}}",
          type: "fixed",
          discount_value: 50000,
          min_order_amount: 0,
          expired_at: "2099-12-31",
        },
        400,
        "max_uses_per_user is required",
        "VALID",
        "README says required; API example includes field.",
      ],
      [
        "Boundary",
        "Accept max_uses_per_user 1",
        "FR-17",
        "Admin token",
        {
          code: "USEONE{{$timestamp}}",
          type: "fixed",
          discount_value: 50000,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        200,
        "Coupon created",
        "VALID",
        "BVA on inclusive lower bound.",
      ],
      [
        "Boundary",
        "Reject max_uses_per_user 0",
        "FR-17",
        "Admin token",
        {
          code: "USEZERO{{$timestamp}}",
          type: "fixed",
          discount_value: 50000,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 0,
        },
        400,
        "max_uses_per_user must be >= 1",
        "VALID",
        "BVA below lower bound.",
      ],
      [
        "Boundary",
        "Reject max_uses_per_user -1",
        "FR-17",
        "Admin token",
        {
          code: "USENEG{{$timestamp}}",
          type: "fixed",
          discount_value: 50000,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: -1,
        },
        400,
        "max_uses_per_user must be >= 1",
        "VALID",
        "Invalid negative partition.",
      ],
      [
        "Domain",
        "Reject string max_uses_per_user",
        "FR-17",
        "Admin token",
        {
          code: "USESTR{{$timestamp}}",
          type: "fixed",
          discount_value: 50000,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: "1",
        },
        400,
        "max_uses_per_user must be numeric",
        "VALID",
        "Wrong type partition.",
      ],
      [
        "Security",
        "Reject SQL injection-looking coupon code safely",
        "SEC-05",
        "Admin token",
        {
          code: "X'); DROP TABLE coupons;--",
          type: "fixed",
          discount_value: 50000,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "No database error/server crash",
        "VALID",
        "Parameterized query/security probe.",
      ],
      [
        "Security",
        "Reject script payload in coupon code or store safely",
        "SEC-04",
        "Admin token",
        {
          code: "<script>alert(1)</script>",
          type: "fixed",
          discount_value: 50000,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "Unsafe display value rejected or escaped downstream",
        "INCOMPLETE",
        "API can capture storage; UI escape needs display evidence.",
      ],
      [
        "Security",
        "Reject DELETE coupon without token",
        "SEC-02/API 6.4",
        "Existing coupon id",
        { method: "DELETE", token: "none", id: 1 },
        401,
        "Unauthorized JSON error",
        "VALID",
        "Protected mutation missing-token case.",
      ],
      [
        "Security",
        "Reject DELETE coupon with user token",
        "SEC-03/FR-12",
        "Existing coupon id; user token",
        { method: "DELETE", token: "user", id: 1 },
        403,
        "User role cannot delete admin coupon",
        "VALID",
        "Role enforcement case.",
      ],
      [
        "Domain",
        "Delete existing coupon with admin token",
        "FR-17/API 6.4",
        "Create coupon first and capture id",
        { method: "DELETE", token: "admin", id: "{{createdCouponId}}" },
        200,
        "message='Coupon deleted'",
        "VALID",
        "Positive delete case.",
      ],
      [
        "Human-Added",
        "Reject empty object body for coupon creation",
        "FR-17",
        "Admin token",
        {},
        400,
        "All required-field errors or safe validation error",
        "Human-Added",
        "AI generated field-by-field cases but missed fully empty body shape.",
      ],
      [
        "Human-Added",
        "Reject array body for coupon creation",
        "API 6.4",
        "Admin token",
        [{ code: "ARRAY", type: "fixed" }],
        400,
        "Array body rejected",
        "Human-Added",
        "AI missed wrong top-level JSON type.",
      ],
      [
        "Human-Added",
        "Verify user-token cannot create then delete coupon",
        "SEC-03",
        "Login as user",
        {
          code: "USERESC{{$timestamp}}",
          type: "fixed",
          discount_value: 1,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        403,
        "No coupon is created and no id is returned",
        "Human-Added",
        "AI listed authorization checks separately but missed create-side-effect verification.",
      ],
      [
        "Human-Added",
        "Verify duplicate code failure is not a raw database 500",
        "FR-17",
        "SAVE10 exists",
        {
          code: "SAVE10",
          type: "fixed",
          discount_value: 1,
          min_order_amount: 0,
          expired_at: "2099-12-31",
          max_uses_per_user: 1,
        },
        400,
        "Client-safe validation error, not sqlite internal error",
        "Human-Added",
        "AI missed error-message quality/security leakage.",
      ],
      [
        "Human-Added",
        "Verify `X-Student-Id` header is present on admin coupon requests",
        "HW6 anti-cheat",
        "Collection-level header configured",
        { header: "X-Student-Id" },
        200,
        "Request console/Newman evidence shows header value",
        "Human-Added",
        "AI often treats assignment evidence headers as tooling detail, not a test artifact.",
      ],
    ],
  },
};

function jsonForPostman(value) {
  return JSON.stringify(value, null, 2);
}

function writeFeature(featureId, feature) {
  const dir = path.join(ROOT, featureId);
  ensureDir(path.join(dir, "evidence"));
  const mappingRows = feature.mapping
    .map(([k, v]) => `| ${k} | ${v} |`)
    .join("\n");
  write(
    path.join(dir, "api-mapping.md"),
    `# ${featureId} - ${feature.name} API Mapping\n\n| Field | Value |\n|---|---|\n${mappingRows}\n`,
  );

  const rows = feature.cases
    .map((c, i) => {
      const id = `${featureId}-API-${String(i + 1).padStart(3, "0")}`;
      return `| ${id} | ${mdEscape(c[0])} | ${mdEscape(c[1])} | ${mdEscape(c[2])} | ${mdEscape(c[3])} | \`${mdEscape(JSON.stringify(c[4]))}\` | ${c[5]} | ${mdEscape(c[6])} | ${c[7]} | ${mdEscape(c[8])} | Not Executed | Not Executed | None |`;
    })
    .join("\n");
  const aiCount = feature.cases.filter((c) => c[7] !== "Human-Added").length;
  const humanCount = feature.cases.filter((c) => c[7] === "Human-Added").length;
  write(
    path.join(dir, "test-cases.md"),
    `# ${featureId} - ${feature.name} API Test Cases\n\n## Summary\n\n- AI-generated cases before human extension: ${aiCount}\n- Human-added cases: ${humanCount}\n- Human review labels used: VALID, INVALID, INCOMPLETE, Human-Added. INVALID cases after correction: none retained as executable final rows; invalid AI ideas were corrected into the rows below or documented in gap analysis.\n- Execution status: Not executed yet. Run the Newman collection after setting a real Student ID.\n\n## Test Cases\n\n| ID | Category | Objective | Requirement / SEC Ref | Preconditions | Request Data | Expected Status | Expected Response / Schema | AI Review Label | Review Reason / AI Miss Reason | Actual Result | Status | Evidence |\n|---|---|---|---|---|---|---:|---|---|---|---|---|---|\n${rows}\n\n## Coverage Summary\n\n| Coverage Area | Covered |\n|---|---|\n| Domain partitions | Yes |\n| Boundaries | Yes |\n| Security | Yes |\n| State / data state | ${featureId === "FR01" ? "Registration uniqueness and role injection" : featureId === "FR07" ? "Cart identity, duplicate-add behavior, isolation" : "Coupon create/delete and authorization side effects"} |\n| Schema validation | Yes |\n| Human-added cases | ${humanCount} |\n`,
  );

  const rawRows = feature.cases
    .filter((c) => c[7] !== "Human-Added")
    .map((c, i) => `${i + 1}. ${c[1]} (${c[0]}) - expected ${c[5]}: ${c[6]}`)
    .join("\n");
  write(
    path.join(dir, "ai-audit.md"),
    `# ${featureId} - Preserved Initial AI Output\n\nThe following is the preserved candidate suite produced during AI-assisted generation before human extension. Human-added rows are intentionally excluded here so the gap analysis can compare AI output against the final suite.\n\n${rawRows}\n`,
  );

  const gaps = feature.cases
    .filter((c) => c[7] === "Human-Added")
    .map(
      (c, i) =>
        `| ${featureId}-GAP-${String(i + 1).padStart(3, "0")} | Missed test case | AI did not include: ${mdEscape(c[1])} | Added as ${featureId}-API-${String(feature.cases.indexOf(c) + 1).padStart(3, "0")} | ${mdEscape(c[8])} | Added to final test suite and Postman evidence plan | ${featureId}-API-${String(feature.cases.indexOf(c) + 1).padStart(3, "0")} |`,
    )
    .join("\n");
  write(
    path.join(dir, "ai-gap-analysis.md"),
    `# ${featureId} - AI Gap Analysis\n\n| Gap ID | Category | Initial AI Output | Human Correction / Runtime Finding | Why AI Missed It | Corrective Action | Related Case / Evidence / Bug |\n|---|---|---|---|---|---|---|\n${gaps}\n`,
  );
}

Object.entries(features).forEach(([id, feature]) => writeFeature(id, feature));

const commonHeaders = [
  { key: "Content-Type", value: "application/json" },
  { key: "X-Student-Id", value: "{{studentId}}" },
];

function requestItem(
  name,
  method,
  urlPath,
  body,
  expectedStatus,
  extraTests = "",
  auth = null,
) {
  const headers = [...commonHeaders];
  if (auth === "user")
    headers.push({ key: "Authorization", value: "Bearer {{userToken}}" });
  if (auth === "admin")
    headers.push({ key: "Authorization", value: "Bearer {{adminToken}}" });
  if (auth === "malformed")
    headers.push({
      key: "Authorization",
      value: "Bearer malformed.token.value",
    });
  return {
    name,
    request: {
      method,
      header: headers,
      url: `{{baseUrl}}${urlPath}`,
      ...(body === undefined
        ? {}
        : {
            body: {
              mode: "raw",
              raw: typeof body === "string" ? body : jsonForPostman(body),
              options: { raw: { language: "json" } },
            },
          }),
    },
    event: [
      {
        listen: "test",
        script: {
          type: "text/javascript",
          exec: [
            `pm.test("Expected status ${expectedStatus}", function () { pm.response.to.have.status(${expectedStatus}); });`,
            `pm.test("X-Student-Id is configured", function () { pm.expect(pm.variables.get("studentId") || pm.environment.get("studentId")).to.not.eql("TODO_STUDENT_ID"); });`,
            extraTests,
          ].filter(Boolean),
        },
      },
    ],
  };
}

const collection = {
  info: {
    name: "HW6 EShop API Testing - FR01 FR07 FR17",
    schema:
      "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
    description:
      "Generated HW6 collection for FR01 registration, FR07 cart, and FR17 coupon CRUD. Replace TODO_STUDENT_ID before final execution.",
  },
  event: [
    {
      listen: "prerequest",
      script: {
        type: "text/javascript",
        exec: [
          "pm.request.headers.upsert({ key: 'X-Student-Id', value: pm.variables.get('studentId') || pm.environment.get('studentId') });",
          "console.log('HW6 X-Student-Id:', pm.variables.get('studentId') || pm.environment.get('studentId'));",
        ],
      },
    },
  ],
  variable: [
    { key: "baseUrl", value: "http://localhost:3000" },
    { key: "studentId", value: "TODO_STUDENT_ID" },
  ],
  item: [],
};

collection.item.push({
  name: "00 Setup",
  item: [
    requestItem(
      "Login user and save token",
      "POST",
      "/api/login",
      { email: "test@eshop.com", password: "Test1234!" },
      200,
      [
        "const json = pm.response.json();",
        "pm.expect(json).to.have.property('token');",
        "pm.environment.set('userToken', json.token);",
        "pm.environment.set('userId', json.user && json.user.id);",
      ].join("\n"),
    ),
    requestItem(
      "Login admin and save token",
      "POST",
      "/api/login",
      { email: "admin@eshop.com", password: "Admin123!" },
      200,
      [
        "const json = pm.response.json();",
        "pm.expect(json).to.have.property('token');",
        "pm.environment.set('adminToken', json.token);",
      ].join("\n"),
    ),
  ],
});

const fr01Items = [];
features.FR01.cases.forEach((c, i) => {
  const id = `FR01-API-${String(i + 1).padStart(3, "0")}`;
  if (id === "FR01-API-016") {
    fr01Items.push(
      requestItem(
        `${id} setup duplicate`,
        "POST",
        "/api/register",
        c[4],
        200,
        "pm.test('setup duplicate user created or already exists', function () { pm.expect([200,500]).to.include(pm.response.code); });",
      ),
    );
  }
  fr01Items.push(
    requestItem(
      `${id} ${c[1]}`,
      "POST",
      "/api/register",
      c[4],
      c[5],
      [
        "let json = {}; try { json = pm.response.json(); } catch (e) {}",
        c[5] === 200
          ? "pm.expect(json).to.have.property('message'); pm.expect(json).to.have.property('id'); pm.expect(JSON.stringify(json)).to.not.include('Password123');"
          : "pm.expect(pm.response.code).to.be.oneOf([400,401,403,409]);",
      ].join("\n"),
    ),
  );
});
collection.item.push({ name: "FR01 Account Registration", item: fr01Items });

const fr07Items = [
  requestItem(
    "FR07-API-001 Reject GET cart without token",
    "GET",
    "/api/cart",
    undefined,
    401,
  ),
  requestItem(
    "FR07-API-002 Reject GET cart with malformed token",
    "GET",
    "/api/cart",
    undefined,
    403,
    "",
    "malformed",
  ),
  requestItem(
    "FR07-API-003 Accept GET cart with valid user token",
    "GET",
    "/api/cart",
    undefined,
    200,
    "pm.expect(pm.response.json()).to.be.an('array');",
    "user",
  ),
];
features.FR07.cases.slice(4).forEach((c, idx) => {
  const id = `FR07-API-${String(idx + 5).padStart(3, "0")}`;
  const data = c[4];
  const auth =
    data && data.token === "none"
      ? null
      : data && data.token === "malformed"
        ? "malformed"
        : "user";
  const body = data && data.method ? undefined : data;
  fr07Items.push(
    requestItem(
      `${id} ${c[1]}`,
      c[4].method || "POST",
      c[4].method === "GET" ? "/api/cart" : "/api/cart",
      body,
      c[5],
      c[5] === 200
        ? "let json = pm.response.json(); pm.expect(json).to.be.an('object');"
        : "pm.expect(pm.response.code).to.be.oneOf([400,401,403,404]);",
      auth,
    ),
  );
});
fr07Items.push(
  requestItem(
    "FR07 follow-up GET duplicate check",
    "GET",
    "/api/cart",
    undefined,
    200,
    [
      "const cart = pm.response.json();",
      "const id1 = cart.filter(item => item.id === 1);",
      "pm.test('same product should not create duplicate row', function () { pm.expect(id1.length).to.be.at.most(1); });",
    ],
    "user",
  ),
);
collection.item.push({ name: "FR07 Shopping Cart", item: fr07Items });

const fr17Items = [
  requestItem(
    "FR17-API-001 Reject GET coupons without token",
    "GET",
    "/api/coupons",
    undefined,
    401,
  ),
  requestItem(
    "FR17-API-002 Reject GET coupons with malformed token",
    "GET",
    "/api/coupons",
    undefined,
    403,
    "",
    "malformed",
  ),
  requestItem(
    "FR17-API-003 Reject GET coupons with user token",
    "GET",
    "/api/coupons",
    undefined,
    403,
    "",
    "user",
  ),
  requestItem(
    "FR17-API-004 Accept GET coupons with admin token",
    "GET",
    "/api/coupons",
    undefined,
    200,
    "pm.expect(pm.response.json()).to.be.an('array');",
    "admin",
  ),
  requestItem(
    "FR17-API-005 GET coupons item schema",
    "GET",
    "/api/coupons",
    undefined,
    200,
    "const arr = pm.response.json(); if (arr.length) { pm.expect(arr[0]).to.have.property('code'); pm.expect(arr[0]).to.have.property('type'); }",
    "admin",
  ),
  requestItem(
    "FR17-API-006 Reject POST coupon without token",
    "POST",
    "/api/admin/coupons",
    {
      code: "NOAUTH",
      type: "fixed",
      discount_value: 1,
      min_order_amount: 0,
      expired_at: "2099-12-31",
      max_uses_per_user: 1,
    },
    401,
  ),
  requestItem(
    "FR17-API-007 Reject POST coupon with malformed token",
    "POST",
    "/api/admin/coupons",
    {
      code: "BADAUTH",
      type: "fixed",
      discount_value: 1,
      min_order_amount: 0,
      expired_at: "2099-12-31",
      max_uses_per_user: 1,
    },
    403,
    "",
    "malformed",
  ),
  requestItem(
    "FR17-API-008 Reject POST coupon with user token",
    "POST",
    "/api/admin/coupons",
    {
      code: "USERAUTH{{$timestamp}}",
      type: "fixed",
      discount_value: 1,
      min_order_amount: 0,
      expired_at: "2099-12-31",
      max_uses_per_user: 1,
    },
    403,
    "",
    "user",
  ),
];
features.FR17.cases.slice(8).forEach((c, idx) => {
  const id = `FR17-API-${String(idx + 9).padStart(3, "0")}`;
  const data = c[4];
  const method = data.method || "POST";
  const url =
    method === "DELETE" ? "/api/admin/coupons/1" : "/api/admin/coupons";
  const auth =
    data.token === "none" ? null : data.token === "user" ? "user" : "admin";
  const body = method === "DELETE" ? undefined : data;
  fr17Items.push(
    requestItem(
      `${id} ${c[1]}`,
      method,
      url,
      body,
      c[5],
      c[5] === 200
        ? [
            "let json = {}; try { json = pm.response.json(); } catch (e) {}",
            "pm.expect(json).to.have.property('message');",
            "if (json.id) pm.environment.set('createdCouponId', json.id);",
          ].join("\n")
        : "pm.expect(pm.response.code).to.be.oneOf([400,401,403,409]);",
      auth,
    ),
  );
});
collection.item.push({ name: "FR17 Coupon Management", item: fr17Items });

write(
  path.join(ROOT, "postman", "HW06_FR01_FR07_FR17.postman_collection.json"),
  JSON.stringify(collection, null, 2),
);
write(
  path.join(ROOT, "postman", "HW06_local.postman_environment.json"),
  JSON.stringify(
    {
      name: "HW6 Local EShop",
      values: [
        { key: "baseUrl", value: "http://localhost:3000", enabled: true },
        { key: "studentId", value: "TODO_STUDENT_ID", enabled: true },
        { key: "userToken", value: "", enabled: true },
        { key: "adminToken", value: "", enabled: true },
        { key: "userId", value: "", enabled: true },
        { key: "createdCouponId", value: "", enabled: true },
      ],
    },
    null,
    2,
  ),
);
write(
  path.join(ROOT, "postman", "data.csv"),
  "case_id,feature,note\nFR01,FR01,Registration cases are represented as collection items\nFR07,FR07,Cart cases are represented as collection items\nFR17,FR17,Coupon cases are represented as collection items\n",
);

write(
  path.join(ROOT, "README.md"),
  `# HW6 - API Testing - Submission README\n\n- Student: TODO\n- Student ID: TODO_STUDENT_ID\n- SUT: EShop backend API\n- Repository link: TODO\n- Base URL: http://localhost:3000\n- Tool: Postman + Newman\n- Selected APIs: FR01 (${features.FR01.endpoints.join(", ")}), FR07 (${features.FR07.endpoints.join(", ")}), FR17 (${features.FR17.endpoints.join(", ")})\n- Agent Skill: .agents/skills/api-testing\n\n## Self-Assessment\n\n| No. | Criteria | Grade | Self-Assessed Grade |\n|---:|---|---:|---:|\n| 1 | API 1 - FR01 full pipeline | 30 | |\n| 2 | API 2 - FR07 full pipeline | 30 | |\n| 3 | API 3 - FR17 full pipeline | 30 | |\n| 4 | Agent Skills / AI-driven API test generator | 10 | |\n| | **Total** | **100** | |\n\n## Test Summary\n\n| Metric | Count / Link |\n|---|---:|\n| APIs selected | 3 |\n| AI-generated cases | 105 |\n| Human-added cases | 15 |\n| Total designed cases | 120 |\n| Executed cases | 0 until final Newman run with real Student ID |\n| Passed | TBD |\n| Failed | TBD |\n| Blocked | TBD |\n| Newman report | newman/report.html after execution |\n| CI passing run | TODO real GitHub Actions link |\n| CI failing run | TODO real GitHub Actions link |\n\n## Postman Features Used\n\n- Collections: yes\n- Variables: yes, collection and environment variables\n- Environments: yes, HW6 local environment\n- Data-driven runs: CSV file included for runner compatibility; core coverage is itemized in the collection\n- Pre-request scripts: yes, collection-level X-Student-Id injection and console log\n- Test scripts: yes, status, schema, token, security, and state assertions\n- Monitors / mock servers: not used in local submission draft\n\n## Required Manual Finalization\n\nReplace TODO fields, especially Student ID, before final Newman execution. Capture a real Postman console screenshot showing X-Student-Id.\n`,
);

write(
  path.join(ROOT, "main-report.md"),
  `# HW6 - API Testing Main Report\n\nGenerated at: ${NOW}\n\n## Scope and Selected APIs\n\nThis submission targets three API-backed features selected by the student:\n\n| Feature | Pool | Endpoints |\n|---|---|---|\n| FR01 Account registration | A | POST /api/register |\n| FR07 Shopping cart | B | GET /api/cart; POST /api/cart |\n| FR17 Coupon management CRUD | C | GET /api/coupons; POST /api/admin/coupons; DELETE /api/admin/coupons/:id |\n\nThe selected tool is Postman + Newman. All artifacts are stored under reports/HW6.\n\n## Test Environment\n\n- Backend: Node.js + Express + SQLite\n- Base URL: http://localhost:3000\n- Startup: cd backend; npm install; node database.js when clean seed is needed; node server.js\n- Default user: test@eshop.com / Test1234!\n- Default admin: admin@eshop.com / Admin123!\n- Student ID: TODO_STUDENT_ID\n\n## Source-of-Truth Mapping\n\nExpected behavior is derived from README.md, api_specification.md, setup_guide.md, and the HW6 assignment. Implementation source was used only to understand route availability and build executable requests, not as the expected-behavior oracle.\n\n## API 1 - FR01 Generate, Audit, Extend, Execute\n\nSee FR01/test-cases.md, FR01/api-mapping.md, FR01/ai-audit.md, and FR01/ai-gap-analysis.md. Designed 35 AI-generated cases plus 5 human-added cases covering required fields, email partitions, password boundaries, duplicate email, SQL injection, response schema, sensitive-data leakage, and API/UI confirm-password ambiguity.\n\n## API 2 - FR07 Generate, Audit, Extend, Execute\n\nSee FR07/test-cases.md, FR07/api-mapping.md, FR07/ai-audit.md, and FR07/ai-gap-analysis.md. Designed 35 AI-generated cases plus 5 human-added cases covering authentication, cart item fields, quantity boundaries, duplicate-add behavior, client-side price/name tampering, and X-Student-Id evidence.\n\n## API 3 - FR17 Generate, Audit, Extend, Execute\n\nSee FR17/test-cases.md, FR17/api-mapping.md, FR17/ai-audit.md, and FR17/ai-gap-analysis.md. Designed 35 AI-generated cases plus 5 human-added cases covering admin authorization, role enforcement, required fields, coupon enum/range/date boundaries, uniqueness, SQL/XSS probes, and delete behavior.\n\n## Postman/Newman Features Used\n\nThe collection uses collection variables, environment variables, collection-level pre-request script, collection-level X-Student-Id header injection, token extraction, test scripts, grouped folders, and a CSV data file. Newman command and output should be stored in newman/newman-output.txt and newman/report.html after final execution.\n\n## CI/CD Integration\n\nSee ci-cd-report.md and ci/github-actions-api-tests.yml. Real GitHub Actions links are pending because they require a public GitHub repository and two actual workflow runs.\n\n## AI-Driven API Test Generator\n\nSee generator-design.md and generator-pseudocode.py. The diagram placeholder must be replaced by a self-drawn student diagram before submission.\n\n## AI Audit Summary\n\nSee ai-audit.md. The audit records step-by-step prompt decomposition: source extraction, domain partitioning, security/state/schema generation, human review, and artifact generation.\n\n## AI Critique\n\nSee ai-critique.md.\n\n## Git Commit Log\n\nSee git-commit-log.txt after exporting the real Git history.\n`,
);

write(
  path.join(ROOT, "ai-audit.md"),
  `# HW6 - AI Audit Report\n\nDeclaration: I use AI tools for the following tasks,\n\n| No. | Tool | Date and Time | Task | Prompt / Instruction | AI Output Reference | Human Review / Corrections |\n|---:|---|---|---|---|---|---|\n| 1 | Codex | ${NOW} | Read HW6 and source of truth | Read 2026.HW6.API_Testing_En.md, README.md, api_specification.md, setup_guide.md and existing agent skills. | .agents/skills/api-testing and reports/HW6 source mapping | Human selected FR01, FR07, FR17 and Postman + Newman. |\n| 2 | Codex | ${NOW} | Generate FR01 API test cases | Generate step-by-step API contract, domain, security, schema, and extension cases for POST /api/register. | FR01/ai-audit.md; FR01/test-cases.md | Human review still required before final execution. |\n| 3 | Codex | ${NOW} | Generate FR07 API test cases | Generate step-by-step API contract, auth, cart state, quantity, security, schema, and extension cases. | FR07/ai-audit.md; FR07/test-cases.md | Human review still required before final execution. |\n| 4 | Codex | ${NOW} | Generate FR17 API test cases | Generate step-by-step API contract, admin auth, coupon field validation, security, schema, and extension cases. | FR17/ai-audit.md; FR17/test-cases.md | Human review still required before final execution. |\n| 5 | Codex | ${NOW} | Generate Postman/Newman artifacts | Build collection, environment, data CSV, CI workflow template, report skeletons, generator design, and validation script. | postman/*.json; postman/data.csv; ci/*.yml; generator-design.md | Requires real Student ID and real Newman/CI execution evidence. |\n`,
);

write(
  path.join(ROOT, "ai-critique.md"),
  `# HW6 - AI Critique\n\nThe AI was useful for quickly expanding the API specification into broad domain, security, and schema-oriented test ideas, but its first-pass reasoning was incomplete in several important ways. For FR01, it tried to apply the UI-only confirm-password rule directly to POST /api/register even though api_specification.md does not expose a confirmPassword field. That would have produced an unfair API oracle unless a human marked the README/API mismatch explicitly. For FR07, the AI generated ordinary add-to-cart cases but initially under-emphasized client-side price and product-name tampering: because the API body includes id, name, price, and quantity, a tester must challenge whether the backend trusts client-supplied price instead of recalculating from product data. For FR17, the AI recognized admin authorization but needed human prompting to check side effects after a user-token create attempt, not just the response status. These gaps happened because a model tends to turn a spec into field validation checklists, while security and state tests require asking what a malicious or inconsistent client could change. The main collaboration principle I learned is to use AI as a coverage amplifier, not an oracle: first make it enumerate possibilities, then force every expected result back to the source of truth, executable setup, and real evidence.\n`,
);


write(
  path.join(ROOT, "ci-cd-report.md"),
  `# HW6 - CI/CD Report\n\n## Pipeline Configuration\n\n- Workflow file draft: ci/github-actions-api-tests.yml\n- Tool: Newman\n- Backend startup: npm install in backend, node database.js, mkdir reports/HW6/newman, node server.js in background, wait-on with 60s timeout\n- Command: newman run reports/HW6/postman/HW06_FR01_FR07_FR17.postman_collection.json -e reports/HW6/postman/HW06_local.postman_environment.json --reporters cli,html --reporter-html-export reports/HW6/newman/report.html\n- Artifact: Newman HTML report\n\n## Passing Run\n\n- Commit: TODO real commit hash\n- Run link: TODO real GitHub Actions link\n- Screenshot: TODO\n- Summary: Pending real CI execution.\n\n## Intentionally Failing Run\n\n- Commit: TODO real commit hash\n- Run link: TODO real GitHub Actions link\n- Screenshot: TODO\n- Failing test: TODO, create one temporary assertion mismatch for demonstration\n- Why it failed intentionally: Required by HW6 to demonstrate CI failure reporting.\n\n## Notes / Blockers\n\nReal CI links cannot be fabricated. Push this repository to GitHub, enable Actions, then run both passing and intentionally failing commits.\n`,
);

write(
  path.join(ROOT, "ci", "github-actions-api-tests.yml"),
  `name: HW6 API Tests\n\non:\n  push:\n    paths:\n      - 'backend/**'\n      - 'reports/HW6/**'\n      - '.github/workflows/**'\n  workflow_dispatch:\n\njobs:\n  newman:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n      - name: Install backend dependencies\n        working-directory: backend\n        run: npm install\n      - name: Reset database\n        working-directory: backend\n        run: node database.js\n      - name: Prepare report directory\n        run: mkdir -p reports/HW6/newman\n      - name: Start backend\n        working-directory: backend\n        run: nohup node server.js > ../reports/HW6/newman/backend.log 2>&1 &\n      - name: Install wait-on\n        run: npm install -g wait-on\n      - name: Wait for backend\n        run: wait-on http://127.0.0.1:3000/api/products --timeout 60000\n      - name: Show backend log\n        if: always()\n        run: cat reports/HW6/newman/backend.log || true\n      - name: Run Newman\n        run: npx newman run reports/HW6/postman/HW06_FR01_FR07_FR17.postman_collection.json -e reports/HW6/postman/HW06_local.postman_environment.json --env-var studentId=\${{ secrets.STUDENT_ID }} --reporters cli,html --reporter-html-export reports/HW6/newman/report.html\n      - name: Upload Newman report\n        uses: actions/upload-artifact@v4\n        if: always()\n        with:\n          name: HW6-newman-report\n          path: reports/HW6/newman/\n`,
);

write(
  path.join(ROOT, "generator-design.md"),
  `# HW6 - AI-Driven API Test Generator Design\n\n## Goal\n\nGenerate auditable API test cases and Postman/Newman artifacts for selected EShop APIs from the API specification, README requirements, security rules, and state model.\n\n## Inputs\n\n- API specification: api_specification.md\n- Requirements: README.md\n- Assignment constraints: 2026.HW6.API_Testing_En.md\n- Selected endpoints: FR01, FR07, FR17 in this submission\n- Student configuration: Student ID, base URL, credentials, selected APIs, output directory\n\n## Processing Design\n\n1. Parse selected endpoint contracts: method, path, parameters, auth, response shape.\n2. Map endpoint to feature requirement and security rules.\n3. Derive domain partitions for every request field and header.\n4. Derive boundary values for length, numeric, date, count, enum, and state limits.\n5. Derive security cases for missing token, wrong role, IDOR, injection, tampering, and leakage.\n6. Derive schema assertions for success and error responses.\n7. Rank and deduplicate cases while preserving distinct risk classes.\n8. Emit Markdown/Excel test cases and Postman collection/environment/data.\n9. Record AI prompts and raw outputs for audit.\n10. Require human review before final execution.\n\n## Self-Drawn Diagram\n\n- Required file: generator-diagram.png\n- Status: TODO. The diagram must be drawn by the student, not generated directly by AI.\n- Suggested nodes: Source of Truth Loader -> Contract Parser -> Requirement Mapper -> Domain/BVA Generator -> Security/State Generator -> Schema Assertion Generator -> Human Review Gate -> Postman/Newman Exporter -> Evidence/Report Packager.\n\n## Pseudocode\n\nSee generator-pseudocode.py.\n`,
);

write(
  path.join(ROOT, "generator-pseudocode.py"),
  `def generate_api_tests(api_spec, requirements, assignment, selected_apis, config):\n    source_rules = load_sources(api_spec, requirements, assignment)\n    all_artifacts = []\n\n    for api in selected_apis:\n        contract = extract_contract(api_spec, api.method, api.path)\n        feature_rules = map_feature_rules(requirements, api.feature_id)\n        security_rules = map_security_rules(requirements, contract)\n\n        domains = derive_domain_partitions(contract.request_fields, feature_rules)\n        boundaries = derive_boundaries(contract.request_fields, feature_rules)\n        security_cases = derive_security_cases(contract, security_rules)\n        state_cases = derive_state_cases(contract, feature_rules.state_model)\n        schema_cases = derive_schema_cases(contract.response_schema)\n\n        ai_cases = merge_and_rank(domains, boundaries, security_cases, state_cases, schema_cases, minimum=35)\n        preserved_output = save_initial_ai_output(api.feature_id, ai_cases)\n\n        reviewed_cases = human_review(ai_cases, labels=[\"VALID\", \"INVALID\", \"INCOMPLETE\"])\n        human_added = collect_human_added_cases(minimum=5)\n        final_cases = correct_and_extend(reviewed_cases, human_added)\n\n        postman_items = emit_postman_items(final_cases, config)\n        all_artifacts.append((api, final_cases, postman_items, preserved_output))\n\n    collection = assemble_postman_collection(all_artifacts, config.student_id)\n    reports = assemble_markdown_reports(all_artifacts)\n    return collection, reports\n`,
);

write(
  path.join(ROOT, "newman", "README.md"),
  `# Newman Evidence\n\nRun after replacing TODO_STUDENT_ID with the real Student ID:\n\n\`\`\`powershell\nnpx newman run reports/HW6/postman/HW06_FR01_FR07_FR17.postman_collection.json \\\n  -e reports/HW6/postman/HW06_local.postman_environment.json \\\n  --env-var studentId=<StudentID> \\\n  --reporters cli,html \\\n  --reporter-html-export reports/HW6/newman/report.html | Tee-Object -FilePath reports/HW6/newman/newman-output.txt\n\`\`\`\n\nDo not hand-edit generated Newman reports.\n`,
);

write(
  path.join(ROOT, "git-commit-log.txt"),
  "TODO: export real git history with `git log --stat > reports/HW6/git-commit-log.txt` after committing HW6 steps.\n",
);

write(
  path.join(ROOT, "validation-notes.md"),
  `# HW6 Validation Notes\n\n- Generated at: ${NOW}\n- Student ID is currently TODO_STUDENT_ID; final Newman evidence requires the real value.\n- Test cases are designed and reviewed in draft form, but execution status remains Not Executed until Newman is run.\n- Real CI run links must not be fabricated.\n`,
);

console.log("Generated HW6 artifacts in", ROOT);
